server:
  port: 8080

spring:
  application:
    name: authentication

  profiles:
    active: prod # Define o profile de produção como padrão

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  swagger-ui:
    configUrl: /v3/api-docs/swagger-config

jwt:
  secret: AWoTYMe+DEu2CahAafxTjDUcgPKmGr84UNWdKqtLt20=
  access-token-expiration: 900000  # 15 minutos (em milissegundos)
  refresh-token-expiration: 604800000  # 7 dias (em milissegundos)

logging:
  level:
    br.com.italo.authentication: DEBUG
    org.springframework.security: DEBUG
